export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_NAVBAR_DROPDOWN = 'TOGGLE_NAVBAR_DROPDOWN';
export const HANDLE_INPUTCHANGE = 'HANDLE_INPUTCHANGE';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';