export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_NAVBAR_DROPDOWN = "TOGGLE_NAVBAR_DROPDOWN";
export const HANDLE_INPUTCHANGE = "HANDLE_INPUTCHANGE";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";
export const DELETE_PROFILE_IMAGE = "DELETE_PROFILE_IMAGE";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SHOW_LOADER = "SHOW_LOADER";
